import Providers from "./Providers";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "imdb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* header */}
          <Header />
          {/* navbar */}
          {/* searchBox */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
